source 'https://github.com/CocoaPods/Specs.git'

target 'BPLoadingMoreControl', :exclusive => true do
  pod "BPLoadingMoreControl", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BPLoadingMoreControl", :path => "../"

  
end
